"""Constants for the Homely integration."""

from typing import Final

from homeassistant.const import (
    CONF_LOCATION,  # noqa: F401
    CONF_PASSWORD,  # noqa: F401
    CONF_USERNAME,  # noqa: F401
    STATE_ALARM_ARMED_AWAY,
    STATE_ALARM_ARMED_HOME,
    STATE_ALARM_ARMED_NIGHT,
    STATE_ALARM_DISARMED,
    STATE_ALARM_PENDING,
    STATE_ALARM_TRIGGERED,
)

DOMAIN: Final = "homely"
DATA_COORDINATOR = "coordinator"

# Translate Homely API alarm state to HA alarm states
HOMELY_TO_HA_ALARM_STATE = {
    "DISARMED": STATE_ALARM_DISARMED,
    "ARMED_AWAY": STATE_ALARM_ARMED_AWAY,
    "ARMED_NIGHT": STATE_ALARM_ARMED_NIGHT,
    "ARMED_STAY": STATE_ALARM_ARMED_HOME,
    "BREACHED": STATE_ALARM_TRIGGERED,
    "ALARM_PENDING": STATE_ALARM_PENDING,
    "ALARM_STAY_PENDING": STATE_ALARM_PENDING,
    "ARMED_NIGHT_PENDING": STATE_ALARM_PENDING,
    "ARMED_AWAY_PENDING": STATE_ALARM_PENDING,
}
